"""Add timestamp and status to ResponderIncident

Revision ID: 636692e2df43
Revises: 7f1554a1395a
Create Date: 2025-06-28 21:43:27.818460

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '636692e2df43'
down_revision = '7f1554a1395a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('responder_incidents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('timestamp', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('responder_incidents', schema=None) as batch_op:
        batch_op.drop_column('timestamp')
        batch_op.drop_column('status')

    # ### end Alembic commands ###
