"""Add status to response_offers

Revision ID: cc0d394856d6
Revises: 55cb47b5b1ac
Create Date: 2025-06-28 20:02:13.648136

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc0d394856d6'
down_revision = '55cb47b5b1ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('response_offers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('response_offers', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
